#find_package(Protobuf REQUIRED)
#if (Protobuf_FOUND)
#    include_directories(${PROTOBUF_INCLUDE_DIR})
#else ()
#    message("Protobuf not found! Run sudo apt-get install libprotoc-dev")
#endif ()
#
#find_package(PCL QUIET)
#if (PCL_FOUND)
#    include_directories(${PCL_INCLUDE_DIRS})
#    link_directories(${PCL_LIBRARY_DIRS})
#    add_definitions(${PCL_DEFINITIONS})
#else ()
#    message("PCL not found!")
#endif ()
#
find_package(BF REQUIRED)
if (BF_FOUND)
    include_directories(${BF_INCLUDE_DIR})
else ()
    message("BF not found!")
endif ()